services:

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "weakPassword" 
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "weakPassword"
    restart: always

volumes:
  mariadb_volume:

